M48
; DRILL file {KiCad 9.0.0} date 2025-03-02T18:09:01-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-02T18:09:01-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X0.4374Y0.26
X0.665Y0.26
T2
X0.9449Y0.1969
M30
